### ISSUE TITLE
EACCES error on format

### ISSUE THREAD

**Issue by tlechman49** [xaverh/vscode-clang-format-provider#125]
Hi I'm having trouble with clang format errors in a workspace.

[2021-10-11 09:30:51.026] [exthost] [error] [xaver.clang-format] provider FAILED
[2021-10-11 09:30:51.026] [exthost] [error] Error: spawn /Users/tlechman/Documents/generic-workspace/clang-format EACCES
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)

I have a clang format file at that level but my file tree also contains submodules in folders that have their own clang format files. Not sure if that is related to the issue. I am specifying ${workspaceRoot}/clang-format as the clang location.

Mac OS Big Sur, most recent vscode and extension, clang version:
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by jmartinez-silabs** [comment]
I am having a similar issue when setting clang-format.executable to my homebrew (macOs) install of clang.
`"clang-format.executable": "/opt/homebrew/opt/llvm@16/bin",` 
![image](https://github.com/xaverh/vscode-clang-format/assets/67972863/5ca0d348-5527-43ac-b4ab-1bc9c68b024d)

I tried to provide full access to the folder and bin with `chmod` and I still get this issue.
