### ISSUE TITLE
Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by Miaowaaaa** [xaverh/vscode-clang-format-provider#92]

**Comment by xaverh** [comment]
Do you have any options set? Which version of clang are you running and can you provide some context to the error message?

**Comment by strike5150** [comment]
I am having the same issue.  VSCode version 1.38.1 and clang-format version 1.9.0.

is there a way to dump the options that are set?

interestingly I have this issue on one machine but not the other.  They are using the same env, WSL + Ubuntu 18.04.  Clearly on one I have settings that cause this but I have no idea how to figure out what.

**Comment by strike5150** [comment]
I was able to recover the following error from the console.  Seems to be an issue with this line
```
~/.vscode-server/extensions/xaver.clang-format-1.9.0/out/src/extension.js:178
child.stdin.end(codeContent);
```

Full error
```
  ERR spawn clang-format EACCES: Error: spawn clang-format EACCES
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
/C:/Users/MyUser/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2542 Error: Cannot read property 'end' of undefined
	at Promise (~/.vscode-server/extensions/xaver.clang-format-1.9.0/out/src/extension.js:178)
	at new Promise (<anonymous>)
	at ClangDocumentFormattingEditProvider.doFormatDocument (~/.vscode-server/extensions/xaver.clang-format-1.9.0/out/src/extension.js:152)
	at ClangDocumentFormattingEditProvider.provideDocumentFormattingEdits (~/.vscode-server/extensions/xaver.clang-format-1.9.0/out/src/extension.js:20)
	at o.asPromise (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:555)
	at Promise (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:55)
	at new Promise (<anonymous>)
	at Object.t.asPromise (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:55)
	at P.provideDocumentFormattingEdits (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:555)
	at _withAdapter.e (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:570)
	at W._withAdapter (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:565)
	at W.$provideDocumentFormattingEdits (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:570)
	at d._doInvokeHandler (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:623)
	at d._invokeHandler (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:623)
	at d._receiveRequest (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:621)
	at d._receiveOneMessage (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:620)
	at _protocol.onMessage.e (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:618)
	at u.fire (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:50)
	at v.fire (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:186)
	at e.onMessage.e (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:783)
	at u.fire (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:50)
	at v.fire (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:186)
	at x._receiveMessage (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:191)
	at _socketDisposables.push._socketReader.onMessage.e (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:188)
	at u.fire (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:50)
	at f.acceptChunk (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:184)
	at _register._socket.onData.e (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:183)
	at Socket.t (~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/vs/server/remoteExtensionHostProcess.js:192)
	at Socket.emit (/C:/Users/MyUser/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/events.js:182)
	at addChunk (/C:/Users/MyUser/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:283)
	at readableAddChunk (/C:/Users/MyUser/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:264)
	at Socket.Readable.push (/C:/Users/MyUser/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:219)
	at TCP.onStreamRead [as onread] (/C:/Users/MyUser/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/internal/stream_base_commons.js:94)
```

**Comment by strike5150** [comment]
I've completely reinstalled and wiped all settings / etensions.  Still getting the error

**Comment by xaverh** [comment]
Still the question remains, which version of `clang` are you using?
```
clang --version
```
