### ISSUE TITLE
Format on save failed with error "Error: Connection got disposed"

### ISSUE THREAD

**Issue by jarodwen** [xaverh/vscode-clang-format-provider#97]
I am using this plugin in a CPP project and got this error after enabling format-on-save:

```
[Error - 12:37:53 PM] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:2898:25)
	at Object.dispose (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:3193:35)
	at LanguageClient.handleConnectionClosed (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:5275:42)
	at LanguageClient.handleConnectionClosed (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:15682:15)
	at closeHandler (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:5262:18)
	at CallbackList.invoke (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:7905:39)
	at Emitter.fire (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:7963:36)
	at closeHandler (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:2248:26)
	at CallbackList.invoke (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:7905:39)
	at Emitter.fire (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:7963:36)
	at StreamMessageReader.fireClose (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:12091:27)
	at Socket.module.exports.listen.readable.on (/home/myname/.vscode/extensions/ms-vscode.cpptools-0.25.1/dist/main.js:12131:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
```

And here is my config for this plugin:

```
{
    "editor.formatOnSave": true,
    "clang-format.style": "google",
    "clang-format.executable": "/usr/bin/clang-format"
}
```

**Comment by rianquinn** [comment]
This might be the same issue:
https://github.com/xaverh/vscode-clang-format-provider/issues/98
